// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/msgr-botanica/Call.tsx": () => import("../components/mockups/msgr-botanica/Call.tsx"),
  "./components/mockups/msgr-botanica/Chat.tsx": () => import("../components/mockups/msgr-botanica/Chat.tsx"),
  "./components/mockups/msgr-botanica/Contacts.tsx": () => import("../components/mockups/msgr-botanica/Contacts.tsx"),
  "./components/mockups/msgr-botanica/Login.tsx": () => import("../components/mockups/msgr-botanica/Login.tsx"),
  "./components/mockups/msgr-botanica/Server.tsx": () => import("../components/mockups/msgr-botanica/Server.tsx"),
  "./components/mockups/msgr-botanica/Version.tsx": () => import("../components/mockups/msgr-botanica/Version.tsx"),
  "./components/mockups/msgr-glass/Call.tsx": () => import("../components/mockups/msgr-glass/Call.tsx"),
  "./components/mockups/msgr-glass/Chat.tsx": () => import("../components/mockups/msgr-glass/Chat.tsx"),
  "./components/mockups/msgr-glass/Contacts.tsx": () => import("../components/mockups/msgr-glass/Contacts.tsx"),
  "./components/mockups/msgr-glass/Login.tsx": () => import("../components/mockups/msgr-glass/Login.tsx"),
  "./components/mockups/msgr-glass/Server.tsx": () => import("../components/mockups/msgr-glass/Server.tsx"),
  "./components/mockups/msgr-glass/Version.tsx": () => import("../components/mockups/msgr-glass/Version.tsx"),
  "./components/mockups/msgr-minimal/Call.tsx": () => import("../components/mockups/msgr-minimal/Call.tsx"),
  "./components/mockups/msgr-minimal/Chat.tsx": () => import("../components/mockups/msgr-minimal/Chat.tsx"),
  "./components/mockups/msgr-minimal/Contacts.tsx": () => import("../components/mockups/msgr-minimal/Contacts.tsx"),
  "./components/mockups/msgr-minimal/Login.tsx": () => import("../components/mockups/msgr-minimal/Login.tsx"),
  "./components/mockups/msgr-minimal/Server.tsx": () => import("../components/mockups/msgr-minimal/Server.tsx"),
  "./components/mockups/msgr-minimal/Version.tsx": () => import("../components/mockups/msgr-minimal/Version.tsx")
};
